version: '3.9'

services:
  server:
    container_name: server
    build:
      context: ./server
    env_file:
      - ./server/.env
    ports:
      - "8000:8000"
  
  client:
    container_name: client
    build:
      context: ./client
    env_file:
      - ./client/.env
    depends_on:
      - server
    ports:
      - "3000:3000"
    links:
      - server